export const ROUTES = {
  login: "/login",
  overview: "/overview",
  departments: "/departments",
  positions: "/positions",
  shifts: "/shifts",
  workSchedule: "/work-schedule",
  attendance: "/attendance",
  payments: "/payments",
  employees: "/employees",
  managerAccounts: "/manager-accounts",
  settings: "/settings",
  myWorkSchedule: "/me/work-schedule",
  myAttendance: "/me/attendance",
  myPayments: "/me/payments",
  myProfile: "/me/profile",
} as const;
